name: Vincent DURMONT Blog
description: Personal blog of Vincent DURMONT
url: http://vdurmont.github.io
highlighter: pygments
markdown: redcarpet
redcarpet:
  input: GMF
excerpt_separator: <!--more-->
